/**
 * ============================================================================
 * CATÁLOGO DE SERVIÇOS — Alooks Hair Studio Tatuapé
 * ============================================================================
 *
 * Coletado em 2026-08-02. Procedência em `scraped-stores/alooks-tatuape/`.
 *
 * FONTE: API pública do Trinks (`estabelecimentos/128264`), página
 * REIVINDICADA pelo lojista, que marcou `exibePreco: true` em todos os 378
 * serviços — o preço é público por decisão dele.
 *
 * A âncora bate por endereço (Itapeti, 518) e, de forma independente, por
 * cruzamento de pessoas: a escala do Trinks lista BILLY, RITA e MARIAH, e as
 * avaliações do Google citam nominalmente os três.
 *
 * NÃO É CARDÁPIO: `orderMode: 'enquiry'`. Preço existe, mas corte de cabelo
 * se agenda — nada aqui vai para um carrinho.
 *
 * NOMES NÃO SÃO TRANSCRIÇÃO LITERAL. O cadastro vem em CAIXA ALTA e sem
 * acento ('DEPILAÇAO', 'ESMALTAÇAO', 'CILIOS', 'MAOS'). Foi aplicada caixa de
 * título e correção ORTOGRÁFICA de acento — nenhuma palavra foi trocada,
 * abreviada ou traduzida. O preço e a duração são o número do cadastro.
 *
 * IMAGENS SÃO GENÉRICAS E DECORATIVAS, uma por categoria. NÃO são fotos desta
 * loja nem do trabalho dela. O acervo real do Google tem 20 itens e apenas 2
 * mostram cabelo — publicar com ele faria um salão de cabelo parecer estúdio
 * de unhas. Foto de resultado, de cliente ou de 'antes e depois' está fora
 * mesmo sendo genérica: seria lida como portfólio da casa.
 * ============================================================================
 */

/*
 * As FORMAS destes dados vivem em `src/lib/types.ts` e são reexportadas aqui
 * por conveniência de import.
 */
export type {
  BadgeTone, Badge, Product, Category, Combo, Review, FAQ, AboutSection,
  NavSection,
} from './types';

import type {
  Product, Category, Combo, Review, FAQ, AboutSection,
} from './types';

/* -------------------------------------------------------------------------- */
/* CATEGORIAS — as 7 do próprio cadastro do lojista, na ordem em que ele as usa */
/* -------------------------------------------------------------------------- */

export const categories: Category[] = [
  { slug: 'cabeleireiro', name: 'Cabeleireiro', emoji: '' },
  { slug: 'depilacao', name: 'Depilação', emoji: '' },
  { slug: 'manicure', name: 'Manicure', emoji: '' },
  { slug: 'sobrancelhas', name: 'Sobrancelhas', emoji: '' },
  { slug: 'depilacao-masculina', name: 'Depilação Masculina', emoji: '' },
  { slug: 'maquiagem', name: 'Maquiagem', emoji: '' },
  { slug: 'noiva', name: 'Noiva', emoji: '' },
];

/* -------------------------------------------------------------------------- */
/* SERVIÇOS — 378 itens                                                        */
/* -------------------------------------------------------------------------- */
/* `description` traz a duração cadastrada, que é o outro dado real da fonte.  */

export const products: Product[] = [
  {
    id: 'alongamento-fita-preenchimento-1kit',
    name: 'Alongamento Fita Preenchimento 1KIT',
    description: 'Duração aproximada de 2h.',
    price: 1820.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'alongamento-manutencao',
    name: 'Alongamento Manutenção',
    description: 'Duração aproximada de 2h.',
    price: 1457.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'alongamento-tirar',
    name: 'Alongamento Tirar',
    description: 'Duração aproximada de 2h.',
    price: 293.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'barba-completa-navalha',
    name: 'Barba Completa (navalha)',
    description: 'Duração aproximada de 45 min.',
    price: 73.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'barba-maquina',
    name: 'Barba Maquina',
    description: 'Duração aproximada de 45 min.',
    price: 29.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'botox-a-1-aux',
    name: 'Botox (a) 1 Aux',
    description: 'Duração aproximada de 2h.',
    price: 120.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'botox-b',
    name: 'Botox (b)',
    description: 'Duração aproximada de 2h.',
    price: 315.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'botox-b-1-aux',
    name: 'Botox (b) 1 Aux',
    description: 'Duração aproximada de 2h.',
    price: 157.50,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'botox-c',
    name: 'Botox (c)',
    description: 'Duração aproximada de 2h.',
    price: 395.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'botox-c-1-aux',
    name: 'Botox (c) 1 Aux',
    description: 'Duração aproximada de 2h.',
    price: 197.50,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'botox-d',
    name: 'Botox (d)',
    description: 'Duração aproximada de 2h.',
    price: 442.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'botox-d-1-aux',
    name: 'Botox (d) 1 Aux',
    description: 'Duração aproximada de 2h.',
    price: 220.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'botox-promo',
    name: 'Botox Promo',
    description: 'Duração aproximada de 2h.',
    price: 231.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'cauterizacao-a',
    name: 'Cauterizacao (a)',
    description: 'Duração aproximada de 2h.',
    price: 278.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'cauterizacao-a-1-aux',
    name: 'Cauterizacao (a) 1 Aux',
    description: 'Duração aproximada de 2h.',
    price: 139.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'cauterizacao-b',
    name: 'Cauterizacao (b)',
    description: 'Duração aproximada de 2h.',
    price: 315.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'cauterizacao-b-1-aux',
    name: 'Cauterizacao (b) 1 Aux',
    description: 'Duração aproximada de 2h.',
    price: 157.50,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'cauterizacao-c',
    name: 'Cauterizacao (c)',
    description: 'Duração aproximada de 2h.',
    price: 369.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'cauterizacao-c-1-aux',
    name: 'Cauterizacao (c) 1 Aux',
    description: 'Duração aproximada de 2h.',
    price: 184.50,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'cauterizacao-d',
    name: 'Cauterizacao (d)',
    description: 'Duração aproximada de 2h.',
    price: 424.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'cauterizacao-d-1-aux',
    name: 'Cauterizacao (d) 1 Aux',
    description: 'Duração aproximada de 2h.',
    price: 212.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'cauterizacao-masc-a',
    name: 'Cauterizacao Masc (a)',
    description: 'Duração aproximada de 2h.',
    price: 135.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'cauterizacao-masc-b',
    name: 'Cauterizacao Masc (b)',
    description: 'Duração aproximada de 2h.',
    price: 150.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'corte-billy',
    name: 'Corte Billy',
    description: 'Duração aproximada de 1h.',
    price: 198.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'corte-billy-franja',
    name: 'Corte Billy Franja',
    description: 'Duração aproximada de 30 min.',
    price: 44.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'corte-billy-infantil',
    name: 'Corte Billy Infantil',
    description: 'Duração aproximada de 1h.',
    price: 105.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'corte-bordado',
    name: 'Corte Bordado',
    description: 'Duração aproximada de 2h.',
    price: 293.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'corte-feminino',
    name: 'Corte Feminino',
    description: 'Duração aproximada de 1h.',
    price: 113.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'corte-franja',
    name: 'Corte Franja',
    description: 'Duração aproximada de 30 min.',
    price: 44.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'corte-infantil-ate-12-anos',
    name: 'Corte Infantil (ate 12 Anos)',
    description: 'Duração aproximada de 1h.',
    price: 77.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'corte-maquina',
    name: 'Corte Maquina',
    description: 'Duração aproximada de 1h.',
    price: 68.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'corte-masculino',
    name: 'Corte Masculino',
    description: 'Duração aproximada de 1h.',
    price: 107.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'corte-masculino-promo',
    name: 'Corte Masculino Promo',
    description: 'Duração aproximada de 1h.',
    price: 58.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'corte-pezinho',
    name: 'Corte Pezinho',
    description: 'Duração aproximada de 30 min.',
    price: 41.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'descoloracao-a',
    name: 'Descoloracao (a)',
    description: 'Duração aproximada de 4h.',
    price: 206.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'descoloracao-b',
    name: 'Descoloracao (b)',
    description: 'Duração aproximada de 4h.',
    price: 260.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'descoloracao-c',
    name: 'Descoloracao (c)',
    description: 'Duração aproximada de 4h.',
    price: 315.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'escova-a',
    name: 'Escova (a)',
    description: 'Duração aproximada de 1h.',
    price: 56.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'escova-a-1-aux',
    name: 'Escova (a) 1 Aux',
    description: 'Duração aproximada de 1h.',
    price: 28.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'escova-b',
    name: 'Escova (b)',
    description: 'Duração aproximada de 1h.',
    price: 68.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'escova-b-1-aux',
    name: 'Escova (b) 1 Aux',
    description: 'Duração aproximada de 1h.',
    price: 34.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'escova-c',
    name: 'Escova (c)',
    description: 'Duração aproximada de 1h.',
    price: 84.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'escova-c-1-aux',
    name: 'Escova (c) 1 Aux',
    description: 'Duração aproximada de 1h.',
    price: 42.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'escova-d',
    name: 'Escova (d)',
    description: 'Duração aproximada de 1h.',
    price: 99.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'escova-d-1-aux',
    name: 'Escova (d) 1 Aux',
    description: 'Duração aproximada de 1h.',
    price: 49.50,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'escova-definitiva-a',
    name: 'Escova Definitiva (a)',
    description: 'Duração aproximada de 2h.',
    price: 1426.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'escova-definitiva-b',
    name: 'Escova Definitiva (b)',
    description: 'Duração aproximada de 2h.',
    price: 1812.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'escova-gradativa-a',
    name: 'Escova Gradativa (a)',
    description: 'Duração aproximada de 2h.',
    price: 319.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'escova-gradativa-a-1-aux',
    name: 'Escova Gradativa (a) 1 Aux',
    description: 'Duração aproximada de 2h.',
    price: 159.50,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'escova-gradativa-b',
    name: 'Escova Gradativa (b)',
    description: 'Duração aproximada de 2h.',
    price: 419.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'escova-gradativa-b-1-aux',
    name: 'Escova Gradativa (b) 1 Aux',
    description: 'Duração aproximada de 2h.',
    price: 209.50,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'escova-gradativa-c',
    name: 'Escova Gradativa (c)',
    description: 'Duração aproximada de 2h.',
    price: 524.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'escova-gradativa-c-1-aux',
    name: 'Escova Gradativa (c) 1 Aux',
    description: 'Duração aproximada de 2h.',
    price: 262.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'escova-gradativa-d',
    name: 'Escova Gradativa (d)',
    description: 'Duração aproximada de 2h.',
    price: 587.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'escova-gradativa-d-1-aux',
    name: 'Escova Gradativa (d) 1 Aux',
    description: 'Duração aproximada de 2h.',
    price: 293.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'escova-gradativa-e',
    name: 'Escova Gradativa (e)',
    description: 'Duração aproximada de 2h.',
    price: 736.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'escova-gradativa-e-1-aux',
    name: 'Escova Gradativa (e) 1 Aux',
    description: 'Duração aproximada de 2h.',
    price: 368.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'escova-mega-hair-a',
    name: 'Escova Mega Hair (a)',
    description: 'Duração aproximada de 1h.',
    price: 113.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'escova-mega-hair-a-1-aux',
    name: 'Escova Mega Hair (a) 1 Aux',
    description: 'Duração aproximada de 1h.',
    price: 56.50,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'escova-mega-hair-b',
    name: 'Escova Mega Hair (b)',
    description: 'Duração aproximada de 1h.',
    price: 133.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'escova-mega-hair-b-1-aux',
    name: 'Escova Mega Hair (b) 1 Aux',
    description: 'Duração aproximada de 1h.',
    price: 66.50,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'escova-mega-hair-c',
    name: 'Escova Mega Hair (c)',
    description: 'Duração aproximada de 1h.',
    price: 151.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'escova-mega-hair-c-1-aux',
    name: 'Escova Mega Hair (c) 1 Aux',
    description: 'Duração aproximada de 1h.',
    price: 75.50,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'escova-promo',
    name: 'Escova Promo',
    description: 'Duração aproximada de 1h.',
    price: 58.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'gommage-lanza',
    name: 'Gommage Lanza',
    description: 'Duração aproximada de 1h.',
    price: 145.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'gradativa-franja-a',
    name: 'Gradativa Franja (a)',
    description: 'Duração aproximada de 1h.',
    price: 109.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'gradativa-franja-a-1-aux',
    name: 'Gradativa Franja (a) 1 Aux',
    description: 'Duração aproximada de 1h.',
    price: 54.50,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'gradativa-franja-b',
    name: 'Gradativa Franja (b)',
    description: 'Duração aproximada de 1h.',
    price: 138.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'gradativa-franja-b-1-aux',
    name: 'Gradativa Franja (b) 1 Aux',
    description: 'Duração aproximada de 1h.',
    price: 69.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'gradativa-franja-c',
    name: 'Gradativa Franja (c)',
    description: 'Duração aproximada de 1h.',
    price: 191.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'gradativa-franja-c-1-aux',
    name: 'Gradativa Franja (c) 1 Aux',
    description: 'Duração aproximada de 1h.',
    price: 95.50,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'gradativa-masculina-a',
    name: 'Gradativa Masculina (a)',
    description: 'Duração aproximada de 1h.',
    price: 190.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'gradativa-masculina-b',
    name: 'Gradativa Masculina (b)',
    description: 'Duração aproximada de 1h.',
    price: 220.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'gradativa-masculina-c',
    name: 'Gradativa Masculina (c)',
    description: 'Duração aproximada de 1h.',
    price: 241.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'hidratacao-step-a',
    name: 'Hidratação Step (a)',
    description: 'Duração aproximada de 1h.',
    price: 157.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'hidratacao-step-a-1-aux',
    name: 'Hidratação Step (a) 1 Aux',
    description: 'Duração aproximada de 1h.',
    price: 78.50,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'hidratacao-step-b',
    name: 'Hidratação Step (b)',
    description: 'Duração aproximada de 1h.',
    price: 194.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'hidratacao-step-b-1-aux',
    name: 'Hidratação Step (b) 1 Aux',
    description: 'Duração aproximada de 1h.',
    price: 97.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'hidratacao-step-c',
    name: 'Hidratação Step (c)',
    description: 'Duração aproximada de 1h.',
    price: 218.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'hidratacao-step-c-1-aux',
    name: 'Hidratação Step (c) 1 Aux',
    description: 'Duração aproximada de 1h.',
    price: 109.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'hidratacao-step-d',
    name: 'Hidratação Step (d)',
    description: 'Duração aproximada de 1h.',
    price: 254.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'hidratacao-step-d-1-aux',
    name: 'Hidratação Step (d) 1 Aux',
    description: 'Duração aproximada de 1h.',
    price: 127.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'hidratacao-step-e',
    name: 'Hidratação Step (e)',
    description: 'Duração aproximada de 1h.',
    price: 296.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'hidratacao-step-e-1-aux',
    name: 'Hidratação Step (e) 1 Aux',
    description: 'Duração aproximada de 1h.',
    price: 148.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'hidratacao-step-f',
    name: 'Hidratação Step (f)',
    description: 'Duração aproximada de 1h.',
    price: 327.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'hidratacao-step-f-1-aux',
    name: 'Hidratação Step (f) 1 Aux',
    description: 'Duração aproximada de 1h.',
    price: 163.50,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'lavado-especial',
    name: 'Lavado Especial',
    description: 'Duração aproximada de 30 min.',
    price: 30.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'luzes-a',
    name: 'Luzes (a)',
    description: 'Duração aproximada de 1h30.',
    price: 284.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'luzes-a-1-aux',
    name: 'Luzes (a) 1 Aux',
    description: 'Duração aproximada de 1h30.',
    price: 142.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'luzes-b',
    name: 'Luzes (b)',
    description: 'Duração aproximada de 1h30.',
    price: 342.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'luzes-b-1-aux',
    name: 'Luzes (b) 1 Aux',
    description: 'Duração aproximada de 1h30.',
    price: 171.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'luzes-c',
    name: 'Luzes (c)',
    description: 'Duração aproximada de 1h30.',
    price: 396.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'luzes-c-1-aux',
    name: 'Luzes (c) 1 Aux',
    description: 'Duração aproximada de 1h30.',
    price: 198.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'luzes-d',
    name: 'Luzes (d)',
    description: 'Duração aproximada de 1h30.',
    price: 487.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'luzes-d-1-aux',
    name: 'Luzes (d) 1 Aux',
    description: 'Duração aproximada de 1h30.',
    price: 243.50,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'luzes-e',
    name: 'Luzes (e)',
    description: 'Duração aproximada de 1h30.',
    price: 565.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'luzes-e-1-aux',
    name: 'Luzes (e) 1 Aux',
    description: 'Duração aproximada de 1h30.',
    price: 282.50,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'mechas-maculino-1-aux',
    name: 'Mechas Maculino 1 Aux',
    description: 'Duração aproximada de 1h30.',
    price: 40.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'mechas-masculino',
    name: 'Mechas Masculino',
    description: 'Duração aproximada de 1h30.',
    price: 80.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'nutricao-wella',
    name: 'Nutrição Wella',
    description: 'Duração aproximada de 1h30.',
    price: 220.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'nutricao-wella-1-aux',
    name: 'Nutrição Wella 1 Aux',
    description: 'Duração aproximada de 1h30.',
    price: 110.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'pack-hydrate-caut-lanza-escova',
    name: 'Pack Hydrate/Caut Lanza/Escova',
    description: 'Duração aproximada de 2h.',
    price: 248.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'pack-luzes-a-1-aux',
    name: 'Pack Luzes (a) 1 Aux',
    description: 'Duração aproximada de 1h30.',
    price: 357.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'pack-luzes-b-1-aux',
    name: 'Pack Luzes (b) 1 Aux',
    description: 'Duração aproximada de 1h30.',
    price: 435.50,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'pack-luzes-c-1-aux',
    name: 'Pack Luzes (c) 1 Aux',
    description: 'Duração aproximada de 1h30.',
    price: 568.50,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'pack-luzes-a',
    name: 'Pack Luzes a',
    description: 'Duração aproximada de 1h30.',
    price: 714.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'pack-luzes-b',
    name: 'Pack Luzes B',
    description: 'Duração aproximada de 1h30.',
    price: 871.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'pack-luzes-c',
    name: 'Pack Luzes C',
    description: 'Duração aproximada de 1h30.',
    price: 1137.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'pack-morena-iluminada',
    name: 'Pack Morena Iluminada',
    description: 'Duração aproximada de 1h30.',
    price: 537.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'pack-nutrition-nutricao-kproescova',
    name: 'Pack Nutrition Nutricao Kproescova',
    description: 'Duração aproximada de 1h30.',
    price: 145.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'papeleta-10-unidades',
    name: 'Papeleta 10 Unidades',
    description: 'Duração aproximada de 1h30.',
    price: 242.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'papeleta-5-unidades',
    name: 'Papeleta 5 Unidades',
    description: 'Duração aproximada de 1h30.',
    price: 121.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'papeleta-unidade',
    name: 'Papeleta Unidade',
    description: 'Duração aproximada de 1h30.',
    price: 24.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'penteado-meio-preso',
    name: 'Penteado Meio Preso',
    description: 'Duração aproximada de 1h.',
    price: 121.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'penteado-meio-preso-1-aux',
    name: 'Penteado Meio Preso 1 Aux',
    description: 'Duração aproximada de 1h.',
    price: 60.50,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'penteado-preso-inteiro',
    name: 'Penteado Preso Inteiro',
    description: 'Duração aproximada de 1h.',
    price: 242.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'penteado-preso-inteiro-1-aux',
    name: 'Penteado Preso Inteiro 1 Aux',
    description: 'Duração aproximada de 1h.',
    price: 121.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'permanente',
    name: 'Permanente',
    description: 'Duração aproximada de 2h.',
    price: 524.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'permanente-1-aux',
    name: 'Permanente 1 Aux',
    description: 'Duração aproximada de 2h.',
    price: 262.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'piastra',
    name: 'Piastra',
    description: 'Duração aproximada de 1h.',
    price: 48.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'piastra-aux-1',
    name: 'Piastra  Aux 1',
    description: 'Duração aproximada de 1h.',
    price: 24.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'preparo-a',
    name: 'Preparo (a)',
    description: 'Duração aproximada de 1h.',
    price: 74.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'preparo-a-1-aux',
    name: 'Preparo (a) 1 Aux',
    description: 'Duração aproximada de 1h.',
    price: 37.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'preparo-b',
    name: 'Preparo (b)',
    description: 'Duração aproximada de 1h.',
    price: 107.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'preparo-b-1-aux',
    name: 'Preparo (b) 1 Aux',
    description: 'Duração aproximada de 1h.',
    price: 53.50,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'preparo-c',
    name: 'Preparo (c)',
    description: 'Duração aproximada de 1h.',
    price: 121.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'preparo-c-1-aux',
    name: 'Preparo (c) 1 Aux',
    description: 'Duração aproximada de 1h.',
    price: 60.50,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'reconstrucao-avlon-a',
    name: 'Reconstrução Avlon (a)',
    description: 'Duração aproximada de 1h30.',
    price: 199.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'reconstrucao-avlon-a-1-aux',
    name: 'Reconstrução Avlon (a) 1 Aux',
    description: 'Duração aproximada de 1h30.',
    price: 99.50,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'reconstrucao-avlon-b',
    name: 'Reconstrução Avlon (b)',
    description: 'Duração aproximada de 1h30.',
    price: 235.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'reconstrucao-avlon-b-1-aux',
    name: 'Reconstrução Avlon (b) 1 Aux',
    description: 'Duração aproximada de 1h30.',
    price: 117.50,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'reconstrucao-avlon-c',
    name: 'Reconstrução Avlon (c)',
    description: 'Duração aproximada de 1h30.',
    price: 254.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'reconstrucao-avlon-c-1-aux',
    name: 'Reconstrução Avlon (c) 1 Aux',
    description: 'Duração aproximada de 1h30.',
    price: 127.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'reconstrucao-avlon-d',
    name: 'Reconstrução Avlon (d)',
    description: 'Duração aproximada de 1h30.',
    price: 284.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'reconstrucao-avlon-d-1-aux',
    name: 'Reconstrução Avlon (d) 1 Aux',
    description: 'Duração aproximada de 1h30.',
    price: 142.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'reconstrucao-avlon-e',
    name: 'Reconstrução Avlon (e)',
    description: 'Duração aproximada de 1h30.',
    price: 320.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'reconstrucao-avlon-e-1-aux',
    name: 'Reconstrução Avlon (e) 1 Aux',
    description: 'Duração aproximada de 1h30.',
    price: 160.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'reconstrucao-avlon-f',
    name: 'Reconstrução Avlon (f)',
    description: 'Duração aproximada de 1h30.',
    price: 356.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'reconstrucao-avlon-f-1-aux',
    name: 'Reconstrução Avlon (f) 1 Aux',
    description: 'Duração aproximada de 1h30.',
    price: 178.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'reconstrucao-wella',
    name: 'Reconstrução Wella',
    description: 'Duração aproximada de 1h.',
    price: 220.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'reconstrucao-wella-1-aux',
    name: 'Reconstrução Wella 1 Aux',
    description: 'Duração aproximada de 1h.',
    price: 110.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'relaxamento-a',
    name: 'Relaxamento (a)',
    description: 'Duração aproximada de 1h30.',
    price: 283.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'relaxamento-a-1-aux',
    name: 'Relaxamento (a) 1 Aux',
    description: 'Duração aproximada de 1h30.',
    price: 141.50,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'relaxamento-b',
    name: 'Relaxamento (b)',
    description: 'Duração aproximada de 1h30.',
    price: 329.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'relaxamento-b-1-aux',
    name: 'Relaxamento (b) 1 Aux',
    description: 'Duração aproximada de 1h30.',
    price: 164.50,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'relaxamento-c',
    name: 'Relaxamento (c)',
    description: 'Duração aproximada de 1h30.',
    price: 373.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'relaxamento-c-1-aux',
    name: 'Relaxamento (c) 1 Aux',
    description: 'Duração aproximada de 1h30.',
    price: 186.50,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'relaxamento-d',
    name: 'Relaxamento (d)',
    description: 'Duração aproximada de 1h30.',
    price: 435.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'relaxamento-d-1-aux',
    name: 'Relaxamento (d) 1 Aux',
    description: 'Duração aproximada de 1h30.',
    price: 217.50,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'relaxamento-e',
    name: 'Relaxamento (e)',
    description: 'Duração aproximada de 1h30.',
    price: 507.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'relaxamento-e-1-aux',
    name: 'Relaxamento (e) 1 Aux',
    description: 'Duração aproximada de 1h30.',
    price: 253.50,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'relaxamento-masculino-a',
    name: 'Relaxamento Masculino  (a)',
    description: 'Duração aproximada de 1h30.',
    price: 114.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'relaxamento-masculino-b',
    name: 'Relaxamento Masculino  (b)',
    description: 'Duração aproximada de 1h30.',
    price: 157.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'relaxamento-masculino-c',
    name: 'Relaxamento Masculino (c)',
    description: 'Duração aproximada de 1h30.',
    price: 194.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'relaxamento-masculino-d',
    name: 'Relaxamento Masculino (d)',
    description: 'Duração aproximada de 1h30.',
    price: 229.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'ritual-kr-chroma-gloss-15-ml',
    name: 'Ritual Kr Chroma Gloss 15 Ml',
    description: 'Duração aproximada de 30 min.',
    price: 254.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'ritual-kr-concentre-fusio-curl',
    name: 'Ritual Kr Concentre Fusio Curl',
    description: 'Duração aproximada de 1h30.',
    price: 361.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'ritual-kr-fusio-reflect-acide-amine',
    name: 'Ritual Kr Fusio Reflect Acide Amine',
    description: 'Duração aproximada de 1h30.',
    price: 361.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'ritual-kr-fusio-resistance',
    name: 'Ritual Kr Fusio Resistance',
    description: 'Duração aproximada de 1h30.',
    price: 361.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'ritual-kr-fusio-transf-nutritive',
    name: 'Ritual Kr Fusio Transf Nutritive',
    description: 'Duração aproximada de 1h30.',
    price: 361.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'ritual-kr-genesis-ampli-force',
    name: 'Ritual Kr Genesis Ampli Force',
    description: 'Duração aproximada de 1h30.',
    price: 361.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'ritual-kr-tratamento-force-architecte-10-grs',
    name: 'Ritual Kr Tratamento Force Architecte 10 Grs',
    description: 'Duração aproximada de 1h30.',
    price: 164.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'ritual-kr-tratamento-force-architecte-20-grs',
    name: 'Ritual Kr Tratamento Force Architecte 20 Grs',
    description: 'Duração aproximada de 1h.',
    price: 237.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'ritual-kr-tratamento-force-architecte-30grs',
    name: 'Ritual Kr Tratamento Force Architecte 30GRS',
    description: 'Duração aproximada de 1h.',
    price: 290.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'ritual-kr-tratamento-masquintanse-10-grs',
    name: 'Ritual Kr Tratamento Masquintanse 10 Grs',
    description: 'Duração aproximada de 30 min.',
    price: 164.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'ritual-kr-tratamento-masquintanse-20g',
    name: 'Ritual Kr Tratamento Masquintanse 20G',
    description: 'Duração aproximada de 30 min.',
    price: 237.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'ritual-kr-tratamento-masquintanse-30g',
    name: 'Ritual Kr Tratamento Masquintanse 30G',
    description: 'Duração aproximada de 30 min.',
    price: 290.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'ritual-kr-tratamento-therapiste-10-grs',
    name: 'Ritual Kr Tratamento Therapiste 10 Grs',
    description: 'Duração aproximada de 1h30.',
    price: 164.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'ritual-kr-tratamento-therapiste-20-grs',
    name: 'Ritual Kr Tratamento Therapiste 20 Grs',
    description: 'Duração aproximada de 1h.',
    price: 237.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'ritual-kr-tratamento-therapiste-30-grs',
    name: 'Ritual Kr Tratamento Therapiste 30 Grs',
    description: 'Duração aproximada de 30 min.',
    price: 290.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'ritual-kr-ultra-violet',
    name: 'Ritual Kr Ultra Violet',
    description: 'Duração aproximada de 1h30.',
    price: 339.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'secar',
    name: 'Secar',
    description: 'Duração aproximada de 30 min.',
    price: 48.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'secar-1-aux',
    name: 'Secar 1 Aux',
    description: 'Duração aproximada de 30 min.',
    price: 24.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'servico-aplicacao',
    name: 'Servico Aplicação',
    description: 'Duração aproximada de 30 min.',
    price: 46.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'servico-tecnico-masculino',
    name: 'Servico Tecnico (masculino)',
    description: 'Duração aproximada de 1h.',
    price: 145.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'servico-tecnico-masculino-1-aux',
    name: 'Servico Tecnico (masculino) 1 Aux',
    description: 'Duração aproximada de 1h.',
    price: 72.50,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'servico-tecnico-promo',
    name: 'Servico Tecnico Promo',
    description: 'Duração aproximada de 1h.',
    price: 160.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'servico-tecnico-promo-1-aux',
    name: 'Servico Tecnico Promo 1 Aux',
    description: 'Duração aproximada de 1h.',
    price: 66.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'servico-tecnico-supreme',
    name: 'Servico Tecnico Supreme',
    description: 'Duração aproximada de 2h.',
    price: 250.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'servico-tecnico-tintura-feminino',
    name: 'Servico Tecnico Tintura Feminino',
    description: 'Duração aproximada de 1h.',
    price: 204.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'servico-tecnico-tintura-feminino-1-aux',
    name: 'Servico Tecnico Tintura Feminino 1 Aux',
    description: 'Duração aproximada de 1h.',
    price: 102.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'taxa-servico-funcionario',
    name: 'Taxa Servico Funcionario',
    description: 'Duração aproximada de 45 min.',
    price: 24.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'terapia-capilar',
    name: 'Terapia Capilar',
    description: 'Duração aproximada de 1h.',
    price: 206.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'teste-de-penteado',
    name: 'Teste de Penteado',
    description: 'Duração aproximada de 1h.',
    price: 160.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'tonalizante-wella',
    name: 'Tonalizante Wella',
    description: 'Duração aproximada de 1h.',
    price: 145.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'tranca-a',
    name: 'Tranca (a)',
    description: 'Duração aproximada de 1h.',
    price: 73.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'trat-avlon-a-1-aux',
    name: 'Trat Avlon (a) 1 Aux',
    description: 'Duração aproximada de 1h30.',
    price: 99.50,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'trat-avlon-b-1-aux',
    name: 'Trat Avlon (b) 1 Aux',
    description: 'Duração aproximada de 1h30.',
    price: 117.50,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'trat-avlon-c-1-aux',
    name: 'Trat Avlon (c) 1 Aux',
    description: 'Duração aproximada de 1h30.',
    price: 127.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'trat-avlon-d-1-aux',
    name: 'Trat Avlon (d) 1 Aux',
    description: 'Duração aproximada de 1h30.',
    price: 142.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'trat-avlon-e-1-aux',
    name: 'Trat Avlon (e) 1 Aux',
    description: 'Duração aproximada de 1h30.',
    price: 160.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'trat-avlon-f-1-aux',
    name: 'Trat Avlon (f) 1 Aux',
    description: 'Duração aproximada de 1h30.',
    price: 178.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'trat-avlon-a',
    name: 'Trat Avlon a',
    description: 'Duração aproximada de 1h30.',
    price: 199.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'trat-avlon-b',
    name: 'Trat Avlon B',
    description: 'Duração aproximada de 1h30.',
    price: 235.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'trat-avlon-c',
    name: 'Trat Avlon C',
    description: 'Duração aproximada de 1h30.',
    price: 254.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'trat-avlon-d',
    name: 'Trat Avlon D',
    description: 'Duração aproximada de 1h30.',
    price: 284.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'trat-avlon-e',
    name: 'Trat Avlon e',
    description: 'Duração aproximada de 1h30.',
    price: 320.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'trat-avlon-f',
    name: 'Trat Avlon F',
    description: 'Duração aproximada de 1h30.',
    price: 356.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'trat-lanza-a',
    name: 'Trat Lanza  a',
    description: 'Duração aproximada de 1h30.',
    price: 113.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'trat-lanza-a-1-aux',
    name: 'Trat Lanza (a) 1 Aux',
    description: 'Duração aproximada de 1h30.',
    price: 56.50,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'trat-lanza-b-1-aux',
    name: 'Trat Lanza (b) 1 Aux',
    description: 'Duração aproximada de 1h30.',
    price: 64.50,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'trat-lanza-c-1-aux',
    name: 'Trat Lanza (c) 1 Aux',
    description: 'Duração aproximada de 1h30.',
    price: 74.50,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'trat-lanza-d-1-aux',
    name: 'Trat Lanza (d) 1 Aux',
    description: 'Duração aproximada de 1h30.',
    price: 87.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'trat-lanza-e-1-aux',
    name: 'Trat Lanza (e) 1 Aux',
    description: 'Duração aproximada de 1h30.',
    price: 103.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'trat-lanza-f-1-aux',
    name: 'Trat Lanza (f) 1 Aux',
    description: 'Duração aproximada de 1h30.',
    price: 124.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'trat-lanza-b',
    name: 'Trat Lanza B',
    description: 'Duração aproximada de 1h30.',
    price: 129.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'trat-lanza-c',
    name: 'Trat Lanza C',
    description: 'Duração aproximada de 1h30.',
    price: 149.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'trat-lanza-d',
    name: 'Trat Lanza D',
    description: 'Duração aproximada de 1h30.',
    price: 174.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'trat-lanza-e',
    name: 'Trat Lanza e',
    description: 'Duração aproximada de 1h30.',
    price: 206.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'trat-lanza-f',
    name: 'Trat Lanza F',
    description: 'Duração aproximada de 1h30.',
    price: 248.00,
    image: '/servicos/cabeleireiro.webp',
    category: 'cabeleireiro',
    available: true,
  },
  {
    id: 'banho-de-lua',
    name: 'Banho de Lua',
    description: 'Duração aproximada de 1h30.',
    price: 168.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'banho-de-lua-rosto-parcial',
    name: 'Banho de Lua Rosto Parcial',
    description: 'Duração aproximada de 1h.',
    price: 61.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'combo-1-meia-perna-vir-compl-buco-ou-ax',
    name: 'Combo 1 (meia Perna+vir Compl+buço Ou Ax)',
    description: 'Duração aproximada de 45 min.',
    price: 141.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'combo-2-perna-int-vir-compl-ax-ou-buco',
    name: 'Combo 2 (perna Int + Vir Compl+ax Ou Buço)',
    description: 'Duração aproximada de 1h.',
    price: 168.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depil-promo-pi-vir-ax',
    name: 'Depil Promo Pi/Vir/Ax',
    description: 'Duração aproximada de 1h30.',
    price: 133.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-axilas-masc',
    name: 'Depilação Axilas Masc.',
    description: 'Duração aproximada de 30 min.',
    price: 44.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-barriga-inteira',
    name: 'Depilação Barriga (inteira)',
    description: 'Duração aproximada de 30 min.',
    price: 36.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-barriga-meia',
    name: 'Depilação Barriga (meia)',
    description: 'Duração aproximada de 30 min.',
    price: 18.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-braco-inteiro',
    name: 'Depilação Braco (inteiro)',
    description: 'Duração aproximada de 30 min.',
    price: 36.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-braco-meio',
    name: 'Depilação Braco (meio)',
    description: 'Duração aproximada de 30 min.',
    price: 26.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-buco',
    name: 'Depilação Buço',
    description: 'Duração aproximada de 15 min.',
    price: 30.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-costa-meia',
    name: 'Depilação Costa (meia)',
    description: 'Duração aproximada de 30 min.',
    price: 24.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-costas-inteira',
    name: 'Depilação Costas (inteira)',
    description: 'Duração aproximada de 30 min.',
    price: 30.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-costeletas',
    name: 'Depilação Costeletas',
    description: 'Duração aproximada de 15 min.',
    price: 19.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-dedos-maos-pes',
    name: 'Depilação Dedos (maos/Pes)',
    description: 'Duração aproximada de 15 min.',
    price: 12.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-entre-coxas-inteira',
    name: 'Depilação Entre Coxas (inteira)',
    description: 'Duração aproximada de 30 min.',
    price: 13.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-entre-coxas-meia',
    name: 'Depilação Entre Coxas (meia)',
    description: 'Duração aproximada de 30 min.',
    price: 22.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-faixa-barriga',
    name: 'Depilação Faixa Barriga',
    description: 'Duração aproximada de 15 min.',
    price: 9.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-faixa-cintura',
    name: 'Depilação Faixa Cintura',
    description: 'Duração aproximada de 15 min.',
    price: 9.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-intima',
    name: 'Depilação Intima',
    description: 'Duração aproximada de 30 min.',
    price: 33.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-linha-alba',
    name: 'Depilação Linha Alba',
    description: 'Duração aproximada de 30 min.',
    price: 3.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-maos-pes',
    name: 'Depilação Mãos/Pés',
    description: 'Duração aproximada de 30 min.',
    price: 13.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-mento',
    name: 'Depilação Mento',
    description: 'Duração aproximada de 15 min.',
    price: 33.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-nadegas-inteira',
    name: 'Depilação Nadegas (inteira)',
    description: 'Duração aproximada de 30 min.',
    price: 34.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-nadegas-meia',
    name: 'Depilação Nadegas (meia)',
    description: 'Duração aproximada de 30 min.',
    price: 17.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-nariz',
    name: 'Depilação Nariz',
    description: 'Duração aproximada de 10 min.',
    price: 18.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-nariz-externo',
    name: 'Depilação Nariz (externo)',
    description: 'Duração aproximada de 10 min.',
    price: 13.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-nuca',
    name: 'Depilação Nuca',
    description: 'Duração aproximada de 15 min.',
    price: 13.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-ombro',
    name: 'Depilação Ombro',
    description: 'Duração aproximada de 30 min.',
    price: 13.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-orelha',
    name: 'Depilação Orelha',
    description: 'Duração aproximada de 10 min.',
    price: 18.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-palpebras',
    name: 'Depilação Palpebras',
    description: 'Duração aproximada de 10 min.',
    price: 13.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-pernas-inteira',
    name: 'Depilação Pernas (inteira)',
    description: 'Duração aproximada de 1h.',
    price: 80.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-pernas-meia',
    name: 'Depilação Pernas (meia)',
    description: 'Duração aproximada de 30 min.',
    price: 53.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-pescoco',
    name: 'Depilação Pescoco',
    description: 'Duração aproximada de 15 min.',
    price: 17.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-posterior-coxa-inteira',
    name: 'Depilação Posterior Coxa (inteira)',
    description: 'Duração aproximada de 15 min.',
    price: 18.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-posterior-coxa-meia',
    name: 'Depilação Posterior Coxa (meia)',
    description: 'Duração aproximada de 15 min.',
    price: 9.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-queixo',
    name: 'Depilação Queixo',
    description: 'Duração aproximada de 15 min.',
    price: 30.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-rosto-completo',
    name: 'Depilação Rosto (completo)',
    description: 'Duração aproximada de 30 min.',
    price: 63.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-rosto-parcial',
    name: 'Depilação Rosto (parcial)',
    description: 'Duração aproximada de 30 min.',
    price: 39.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-seios-areolas',
    name: 'Depilação Seios (areolas)',
    description: 'Duração aproximada de 15 min.',
    price: 12.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-seios-inteiro',
    name: 'Depilação Seios (inteiro)',
    description: 'Duração aproximada de 15 min.',
    price: 17.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-testa',
    name: 'Depilação Testa',
    description: 'Duração aproximada de 15 min.',
    price: 13.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-torax',
    name: 'Depilação Torax',
    description: 'Duração aproximada de 30 min.',
    price: 24.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-virilha-intima',
    name: 'Depilação Virilha (intima)',
    description: 'Duração aproximada de 30 min.',
    price: 69.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'depilacao-virilha-remocao-total',
    name: 'Depilação Virilha (remocao Total)',
    description: 'Duração aproximada de 30 min.',
    price: 88.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'diferenca-meia-perna-p-inteira',
    name: 'Diferenca Meia Perna P Inteira',
    description: 'Duração aproximada de 30 min.',
    price: 26.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'diferenca-virilha-intima-p-remocao',
    name: 'Diferenca Virilha Intima P/Remocao',
    description: 'Duração aproximada de 30 min.',
    price: 8.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'promo-buco-valido-p-trio-promocao',
    name: 'Promo Buço-Valido P/ Trio Promocao',
    description: 'Duração aproximada de 1h.',
    price: 22.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'promo-mp-valido-p-trio-promocao',
    name: 'Promo Mp-Valido P/ Trio Promocao',
    description: 'Duração aproximada de 45 min.',
    price: 36.00,
    image: '/servicos/depilacao.webp',
    category: 'depilacao',
    available: true,
  },
  {
    id: 'esfoliacao-maos',
    name: 'Esfoliacao Mãos',
    description: 'Duração aproximada de 30 min.',
    price: 21.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'esmaltacao-em-gel',
    name: 'Esmaltação em Gel',
    description: 'Duração aproximada de 3h.',
    price: 110.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'joia-aplicacao',
    name: 'Joia Aplicação',
    description: 'Duração aproximada de 30 min.',
    price: 17.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'manicure',
    name: 'Manicure',
    description: 'Duração aproximada de 1h.',
    price: 41.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'manicure-aplique',
    name: 'Manicure Aplique',
    description: 'Duração aproximada de 1h.',
    price: 4.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'manicure-banho-de-porcelana',
    name: 'Manicure Banho de Porcelana',
    description: 'Duração aproximada de 1h30.',
    price: 161.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'manicure-banho-em-gel',
    name: 'Manicure Banho em Gel',
    description: 'Duração aproximada de 2h.',
    price: 229.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'manicure-craquelada',
    name: 'Manicure Craquelada',
    description: 'Duração aproximada de 30 min.',
    price: 34.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'manicure-decorada',
    name: 'Manicure Decorada',
    description: 'Duração aproximada de 1h.',
    price: 39.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'manicure-decorada-com-cristal',
    name: 'Manicure Decorada com Cristal',
    description: 'Duração aproximada de 1h.',
    price: 5.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'manicure-espanhola',
    name: 'Manicure Espanhola',
    description: 'Duração aproximada de 1h.',
    price: 110.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'manicure-fibra-de-vidro-remocao',
    name: 'Manicure Fibra de Vidro Remocao',
    description: 'Duração aproximada de 45 min.',
    price: 65.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'manicure-flor',
    name: 'Manicure Flor',
    description: 'Duração aproximada de 15 min.',
    price: 4.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'manicure-flor-2',
    name: 'Manicure Flor 2',
    description: 'Duração aproximada de 15 min.',
    price: 5.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'manicure-francesinha',
    name: 'Manicure Francesinha',
    description: 'Duração aproximada de 1h.',
    price: 51.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'manicure-francesinha-pintar',
    name: 'Manicure Francesinha Pintar',
    description: 'Duração aproximada de 30 min.',
    price: 21.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'manicure-gel-unidade',
    name: 'Manicure Gel Unidade',
    description: 'Duração aproximada de 45 min.',
    price: 41.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'manicure-hightech',
    name: 'Manicure Hightech',
    description: 'Duração aproximada de 45 min.',
    price: 68.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'manicure-manutencao-alongamento',
    name: 'Manicure Manutenção Alongamento',
    description: 'Duração aproximada de 3h.',
    price: 229.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'manicure-nova-york',
    name: 'Manicure Nova York',
    description: 'Duração aproximada de 2h.',
    price: 243.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'manicure-pintar',
    name: 'Manicure Pintar',
    description: 'Duração aproximada de 30 min.',
    price: 18.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'manicure-polimento',
    name: 'Manicure Polimento',
    description: 'Duração aproximada de 1h.',
    price: 48.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'manicure-porcelana-f1',
    name: 'Manicure Porcelana F1',
    description: 'Duração aproximada de 3h.',
    price: 201.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'manicure-porcelana-f1-tirar',
    name: 'Manicure Porcelana F1  Tirar',
    description: 'Duração aproximada de 3h.',
    price: 39.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'manicure-porcelana-f1-manutencao',
    name: 'Manicure Porcelana F1 Manutenção',
    description: 'Duração aproximada de 3h.',
    price: 202.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'manicure-porcelana-f1-unidade',
    name: 'Manicure Porcelana F1 Unidade',
    description: 'Duração aproximada de 3h.',
    price: 161.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'manicure-promo',
    name: 'Manicure Promo',
    description: 'Duração aproximada de 1h.',
    price: 35.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'manicure-strass',
    name: 'Manicure Strass',
    description: 'Duração aproximada de 15 min.',
    price: 4.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'manicure-unha-postica',
    name: 'Manicure Unha Postica',
    description: 'Duração aproximada de 2h.',
    price: 110.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'manicure-unha-postica-unidade',
    name: 'Manicure Unha Postica Unidade',
    description: 'Duração aproximada de 30 min.',
    price: 11.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'manutencao-banho-em-gel',
    name: 'Manutenção Banho em Gel',
    description: 'Duração aproximada de 3h.',
    price: 161.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'manutencao-espanhola',
    name: 'Manutenção Espanhola',
    description: 'Duração aproximada de 1h.',
    price: 35.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'manutencao-unidade',
    name: 'Manutenção Unidade',
    description: 'Duração aproximada de 30 min.',
    price: 20.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'pedicure',
    name: 'Pedicure',
    description: 'Duração aproximada de 1h.',
    price: 51.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'pedicure-desencravar',
    name: 'Pedicure Desencravar',
    description: 'Duração aproximada de 1h.',
    price: 13.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'pedicure-esfoliacao',
    name: 'Pedicure Esfoliação',
    description: 'Duração aproximada de 30 min.',
    price: 35.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'pedicure-francesinha',
    name: 'Pedicure Francesinha',
    description: 'Duração aproximada de 1h.',
    price: 65.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'pedicure-francesinha-pintar',
    name: 'Pedicure Francesinha Pintar',
    description: 'Duração aproximada de 30 min.',
    price: 34.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'pedicure-hightech',
    name: 'Pedicure Hightech',
    description: 'Duração aproximada de 1h.',
    price: 64.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'pedicure-pintar',
    name: 'Pedicure Pintar',
    description: 'Duração aproximada de 30 min.',
    price: 26.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'pedicure-polimento',
    name: 'Pedicure Polimento',
    description: 'Duração aproximada de 1h.',
    price: 66.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'pedicure-promo',
    name: 'Pedicure Promo',
    description: 'Duração aproximada de 1h.',
    price: 44.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'plastica-dos-pes-completa',
    name: 'Plastica dos Pés Completa',
    description: 'Duração aproximada de 2h.',
    price: 99.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'plastica-dos-pes-parcial',
    name: 'Plastica dos Pés Parcial',
    description: 'Duração aproximada de 2h.',
    price: 63.00,
    image: '/servicos/manicure.webp',
    category: 'manicure',
    available: true,
  },
  {
    id: 'alongamento-cilios-manutecao',
    name: 'Alongamento Cílios Manutecao',
    description: 'Duração aproximada de 2h.',
    price: 151.00,
    image: '/servicos/sobrancelhas.webp',
    category: 'sobrancelhas',
    available: true,
  },
  {
    id: 'alongamento-de-cilios',
    name: 'Alongamento de Cílios',
    description: 'Duração aproximada de 2h.',
    price: 310.00,
    image: '/servicos/sobrancelhas.webp',
    category: 'sobrancelhas',
    available: true,
  },
  {
    id: 'aplicacao-de-henna',
    name: 'Aplicação de Henna',
    description: 'Duração aproximada de 1h.',
    price: 66.00,
    image: '/servicos/sobrancelhas.webp',
    category: 'sobrancelhas',
    available: true,
  },
  {
    id: 'cilios-posticos-cliente',
    name: 'Cílios Posticos (cliente)',
    description: 'Duração aproximada de 30 min.',
    price: 42.00,
    image: '/servicos/sobrancelhas.webp',
    category: 'sobrancelhas',
    available: true,
  },
  {
    id: 'cilios-posticos-do-salao',
    name: 'Cílios Posticos (do Salao)',
    description: 'Duração aproximada de 30 min.',
    price: 84.00,
    image: '/servicos/sobrancelhas.webp',
    category: 'sobrancelhas',
    available: true,
  },
  {
    id: 'depil-buco',
    name: 'Depil Buço',
    description: 'Duração aproximada de 15 min.',
    price: 30.00,
    image: '/servicos/sobrancelhas.webp',
    category: 'sobrancelhas',
    available: true,
  },
  {
    id: 'depil-costeleta',
    name: 'Depil Costeleta',
    description: 'Duração aproximada de 30 min.',
    price: 20.00,
    image: '/servicos/sobrancelhas.webp',
    category: 'sobrancelhas',
    available: true,
  },
  {
    id: 'depil-egipcia-buco',
    name: 'Depil Egipcia Buço',
    description: 'Duração aproximada de 30 min.',
    price: 40.00,
    image: '/servicos/sobrancelhas.webp',
    category: 'sobrancelhas',
    available: true,
  },
  {
    id: 'depil-egipcia-cost-buco-queixo',
    name: 'Depil Egipcia Cost Buço Queixo',
    description: 'Duração aproximada de 30 min.',
    price: 64.00,
    image: '/servicos/sobrancelhas.webp',
    category: 'sobrancelhas',
    available: true,
  },
  {
    id: 'depil-egipcia-mentos',
    name: 'Depil Egipcia Mentos',
    description: 'Duração aproximada de 30 min.',
    price: 34.00,
    image: '/servicos/sobrancelhas.webp',
    category: 'sobrancelhas',
    available: true,
  },
  {
    id: 'depil-egipcia-rosto-buco',
    name: 'Depil Egipcia Rosto Buço',
    description: 'Duração aproximada de 30 min.',
    price: 76.00,
    image: '/servicos/sobrancelhas.webp',
    category: 'sobrancelhas',
    available: true,
  },
  {
    id: 'depil-egipcia-sobrancelha',
    name: 'Depil Egipcia Sobrancelha',
    description: 'Duração aproximada de 30 min.',
    price: 84.00,
    image: '/servicos/sobrancelhas.webp',
    category: 'sobrancelhas',
    available: true,
  },
  {
    id: 'depil-mento',
    name: 'Depil Mento',
    description: 'Duração aproximada de 15 min.',
    price: 33.00,
    image: '/servicos/sobrancelhas.webp',
    category: 'sobrancelhas',
    available: true,
  },
  {
    id: 'depil-nariz',
    name: 'Depil Nariz',
    description: 'Duração aproximada de 15 min.',
    price: 18.00,
    image: '/servicos/sobrancelhas.webp',
    category: 'sobrancelhas',
    available: true,
  },
  {
    id: 'depil-nariz-externo',
    name: 'Depil Nariz Externo',
    description: 'Duração aproximada de 15 min.',
    price: 13.00,
    image: '/servicos/sobrancelhas.webp',
    category: 'sobrancelhas',
    available: true,
  },
  {
    id: 'depil-palpebras',
    name: 'Depil Palpebras',
    description: 'Duração aproximada de 15 min.',
    price: 13.00,
    image: '/servicos/sobrancelhas.webp',
    category: 'sobrancelhas',
    available: true,
  },
  {
    id: 'depil-queixo',
    name: 'Depil Queixo',
    description: 'Duração aproximada de 15 min.',
    price: 30.00,
    image: '/servicos/sobrancelhas.webp',
    category: 'sobrancelhas',
    available: true,
  },
  {
    id: 'depil-rosto-completo',
    name: 'Depil Rosto Completo',
    description: 'Duração aproximada de 30 min.',
    price: 63.00,
    image: '/servicos/sobrancelhas.webp',
    category: 'sobrancelhas',
    available: true,
  },
  {
    id: 'depil-testa',
    name: 'Depil Testa',
    description: 'Duração aproximada de 30 min.',
    price: 13.00,
    image: '/servicos/sobrancelhas.webp',
    category: 'sobrancelhas',
    available: true,
  },
  {
    id: 'despigmentacao-de-sobrancelhas',
    name: 'Despigmentacao de Sobrancelhas',
    description: 'Duração aproximada de 2h.',
    price: 424.00,
    image: '/servicos/sobrancelhas.webp',
    category: 'sobrancelhas',
    available: true,
  },
  {
    id: 'hidragloss',
    name: 'Hidragloss',
    description: 'Duração aproximada de 1h30.',
    price: 303.00,
    image: '/servicos/sobrancelhas.webp',
    category: 'sobrancelhas',
    available: true,
  },
  {
    id: 'micropig-revitalizacao-labial',
    name: 'Micropig  Revitalizacao Labial',
    description: 'Duração aproximada de 2h.',
    price: 959.00,
    image: '/servicos/sobrancelhas.webp',
    category: 'sobrancelhas',
    available: true,
  },
  {
    id: 'micropig-de-falhas-a',
    name: 'Micropig de Falhas (a)',
    description: 'Duração aproximada de 2h.',
    price: 265.00,
    image: '/servicos/sobrancelhas.webp',
    category: 'sobrancelhas',
    available: true,
  },
  {
    id: 'micropig-de-falhas-b',
    name: 'Micropig de Falhas (b)',
    description: 'Duração aproximada de 2h.',
    price: 410.00,
    image: '/servicos/sobrancelhas.webp',
    category: 'sobrancelhas',
    available: true,
  },
  {
    id: 'micropig-retoque-45-60',
    name: 'Micropig Retoque 45/60',
    description: 'Duração aproximada de 2h.',
    price: 385.00,
    image: '/servicos/sobrancelhas.webp',
    category: 'sobrancelhas',
    available: true,
  },
  {
    id: 'micropig-retoque-65-90',
    name: 'Micropig Retoque 65/90',
    description: 'Duração aproximada de 2h.',
    price: 475.00,
    image: '/servicos/sobrancelhas.webp',
    category: 'sobrancelhas',
    available: true,
  },
  {
    id: 'permanente-de-cilios',
    name: 'Permanente de Cílios',
    description: 'Duração aproximada de 1h.',
    price: 160.00,
    image: '/servicos/sobrancelhas.webp',
    category: 'sobrancelhas',
    available: true,
  },
  {
    id: 'sob-buco-promo',
    name: 'Sob + Buço Promo',
    description: 'Duração aproximada de 30 min.',
    price: 88.00,
    image: '/servicos/sobrancelhas.webp',
    category: 'sobrancelhas',
    available: true,
  },
  {
    id: 'sobrancelhas',
    name: 'Sobrancelhas',
    description: 'Duração aproximada de 15 min.',
    price: 84.00,
    image: '/servicos/sobrancelhas.webp',
    category: 'sobrancelhas',
    available: true,
  },
  {
    id: 'sobrancelhas-de-henna',
    name: 'Sobrancelhas de Henna',
    description: 'Duração aproximada de 30 min.',
    price: 133.00,
    image: '/servicos/sobrancelhas.webp',
    category: 'sobrancelhas',
    available: true,
  },
  {
    id: 'sobrancelhas-tingir',
    name: 'Sobrancelhas Tingir',
    description: 'Duração aproximada de 30 min.',
    price: 30.00,
    image: '/servicos/sobrancelhas.webp',
    category: 'sobrancelhas',
    available: true,
  },
  {
    id: 'tintura-de-cilios',
    name: 'Tintura de Cílios',
    description: 'Duração aproximada de 30 min.',
    price: 62.00,
    image: '/servicos/sobrancelhas.webp',
    category: 'sobrancelhas',
    available: true,
  },
  {
    id: 'abdomen',
    name: 'Abdomen',
    description: 'Duração aproximada de 45 min.',
    price: 61.00,
    image: '/servicos/depilacao-masculina.webp',
    category: 'depilacao-masculina',
    available: true,
  },
  {
    id: 'abdomen-meio',
    name: 'Abdomen (meio)',
    description: 'Duração aproximada de 45 min.',
    price: 37.00,
    image: '/servicos/depilacao-masculina.webp',
    category: 'depilacao-masculina',
    available: true,
  },
  {
    id: 'abdomen-masculino',
    name: 'Abdomen Masculino',
    description: 'Duração aproximada de 30 min.',
    price: 55.00,
    image: '/servicos/depilacao-masculina.webp',
    category: 'depilacao-masculina',
    available: true,
  },
  {
    id: 'aplicacao-de-maquina-corpo-todo',
    name: 'Aplicação de Maquina Corpo Todo',
    description: 'Duração aproximada de 45 min.',
    price: 35.00,
    image: '/servicos/depilacao-masculina.webp',
    category: 'depilacao-masculina',
    available: true,
  },
  {
    id: 'aplicacao-de-maquina-costas',
    name: 'Aplicação de Maquina Costas',
    description: 'Duração aproximada de 30 min.',
    price: 10.00,
    image: '/servicos/depilacao-masculina.webp',
    category: 'depilacao-masculina',
    available: true,
  },
  {
    id: 'aplicacao-de-maquina-coxas',
    name: 'Aplicação de Maquina Coxas',
    description: 'Duração aproximada de 30 min.',
    price: 13.00,
    image: '/servicos/depilacao-masculina.webp',
    category: 'depilacao-masculina',
    available: true,
  },
  {
    id: 'axilas-femininas',
    name: 'Axilas Femininas',
    description: 'Duração aproximada de 30 min.',
    price: 36.00,
    image: '/servicos/depilacao-masculina.webp',
    category: 'depilacao-masculina',
    available: true,
  },
  {
    id: 'braco-meio',
    name: 'Braço (meio)',
    description: 'Duração aproximada de 45 min.',
    price: 44.00,
    image: '/servicos/depilacao-masculina.webp',
    category: 'depilacao-masculina',
    available: true,
  },
  {
    id: 'braco-inteiro',
    name: 'Braço Inteiro',
    description: 'Duração aproximada de 45 min.',
    price: 61.00,
    image: '/servicos/depilacao-masculina.webp',
    category: 'depilacao-masculina',
    available: true,
  },
  {
    id: 'costas',
    name: 'Costas',
    description: 'Duração aproximada de 45 min.',
    price: 78.00,
    image: '/servicos/depilacao-masculina.webp',
    category: 'depilacao-masculina',
    available: true,
  },
  {
    id: 'costas-meia',
    name: 'Costas (meia)',
    description: 'Duração aproximada de 45 min.',
    price: 44.00,
    image: '/servicos/depilacao-masculina.webp',
    category: 'depilacao-masculina',
    available: true,
  },
  {
    id: 'depil-masculino-barba-cst-fc',
    name: 'Depil Masculino Barba (cst+fc)',
    description: 'Duração aproximada de 45 min.',
    price: 56.00,
    image: '/servicos/depilacao-masculina.webp',
    category: 'depilacao-masculina',
    available: true,
  },
  {
    id: 'depil-masculino-barba-cst-fc-big',
    name: 'Depil Masculino Barba (cst+fc+big)',
    description: 'Duração aproximada de 45 min.',
    price: 73.00,
    image: '/servicos/depilacao-masculina.webp',
    category: 'depilacao-masculina',
    available: true,
  },
  {
    id: 'depil-masculino-barba-cst-fc-big-pc',
    name: 'Depil Masculino Barba(cst+fc+big+pc',
    description: 'Duração aproximada de 45 min.',
    price: 119.00,
    image: '/servicos/depilacao-masculina.webp',
    category: 'depilacao-masculina',
    available: true,
  },
  {
    id: 'depil-masculino-barba-cst-fc-big-qx',
    name: 'Depil Masculino Barba(cst+fc+big+qx',
    description: 'Duração aproximada de 45 min.',
    price: 89.00,
    image: '/servicos/depilacao-masculina.webp',
    category: 'depilacao-masculina',
    available: true,
  },
  {
    id: 'depil-masculino-bigode',
    name: 'Depil Masculino Bigode',
    description: 'Duração aproximada de 45 min.',
    price: 44.00,
    image: '/servicos/depilacao-masculina.webp',
    category: 'depilacao-masculina',
    available: true,
  },
  {
    id: 'depil-masculino-costa-inteira',
    name: 'Depil Masculino Costa (inteira)',
    description: 'Duração aproximada de 45 min.',
    price: 66.00,
    image: '/servicos/depilacao-masculina.webp',
    category: 'depilacao-masculina',
    available: true,
  },
  {
    id: 'depil-masculino-costeletas',
    name: 'Depil Masculino Costeletas',
    description: 'Duração aproximada de 45 min.',
    price: 36.00,
    image: '/servicos/depilacao-masculina.webp',
    category: 'depilacao-masculina',
    available: true,
  },
  {
    id: 'depil-masculino-parcial-media',
    name: 'Depil Masculino Parcial Media',
    description: 'Duração aproximada de 30 min.',
    price: 24.00,
    image: '/servicos/depilacao-masculina.webp',
    category: 'depilacao-masculina',
    available: true,
  },
  {
    id: 'depil-masculino-parcial-pequena',
    name: 'Depil Masculino Parcial Pequena',
    description: 'Duração aproximada de 30 min.',
    price: 21.00,
    image: '/servicos/depilacao-masculina.webp',
    category: 'depilacao-masculina',
    available: true,
  },
  {
    id: 'depil-masculino-pes-ou-maos',
    name: 'Depil Masculino Pés Ou Mãos',
    description: 'Duração aproximada de 30 min.',
    price: 25.00,
    image: '/servicos/depilacao-masculina.webp',
    category: 'depilacao-masculina',
    available: true,
  },
  {
    id: 'depil-masculino-sobrecilio-aparar',
    name: 'Depil Masculino Sobrecilio Aparar',
    description: 'Duração aproximada de 30 min.',
    price: 29.00,
    image: '/servicos/depilacao-masculina.webp',
    category: 'depilacao-masculina',
    available: true,
  },
  {
    id: 'depil-masculino-sobrecilio-simples',
    name: 'Depil Masculino Sobrecilio Simples',
    description: 'Duração aproximada de 45 min.',
    price: 40.00,
    image: '/servicos/depilacao-masculina.webp',
    category: 'depilacao-masculina',
    available: true,
  },
  {
    id: 'genitalha-masculina',
    name: 'Genitalha Masculina',
    description: 'Duração aproximada de 1h.',
    price: 182.00,
    image: '/servicos/depilacao-masculina.webp',
    category: 'depilacao-masculina',
    available: true,
  },
  {
    id: 'intima-masculina',
    name: 'Intima Masculina',
    description: 'Duração aproximada de 45 min.',
    price: 51.00,
    image: '/servicos/depilacao-masculina.webp',
    category: 'depilacao-masculina',
    available: true,
  },
  {
    id: 'nadegas-masculina',
    name: 'Nadegas Masculina',
    description: 'Duração aproximada de 45 min.',
    price: 61.00,
    image: '/servicos/depilacao-masculina.webp',
    category: 'depilacao-masculina',
    available: true,
  },
  {
    id: 'perna-inteira-masculina',
    name: 'Perna Inteira Masculina',
    description: 'Duração aproximada de 1h30.',
    price: 169.00,
    image: '/servicos/depilacao-masculina.webp',
    category: 'depilacao-masculina',
    available: true,
  },
  {
    id: 'torax-meio-masculina',
    name: 'Torax (meio) Masculina',
    description: 'Duração aproximada de 45 min.',
    price: 54.00,
    image: '/servicos/depilacao-masculina.webp',
    category: 'depilacao-masculina',
    available: true,
  },
  {
    id: 'torax-masculina',
    name: 'Torax Masculina',
    description: 'Duração aproximada de 45 min.',
    price: 73.00,
    image: '/servicos/depilacao-masculina.webp',
    category: 'depilacao-masculina',
    available: true,
  },
  {
    id: 'maquiagem-c-cilios-salao',
    name: 'Maquiagem C Cílios Salao',
    description: 'Duração aproximada de 1h.',
    price: 266.00,
    image: '/servicos/maquiagem.webp',
    category: 'maquiagem',
    available: true,
  },
  {
    id: 'maquiagem-infantil',
    name: 'Maquiagem Infantil',
    description: 'Duração aproximada de 1h.',
    price: 84.00,
    image: '/servicos/maquiagem.webp',
    category: 'maquiagem',
    available: true,
  },
  {
    id: 'maquiagem-masculina',
    name: 'Maquiagem Masculina',
    description: 'Duração aproximada de 1h.',
    price: 107.00,
    image: '/servicos/maquiagem.webp',
    category: 'maquiagem',
    available: true,
  },
  {
    id: 'maquiagem-olhos',
    name: 'Maquiagem Olhos',
    description: 'Duração aproximada de 1h.',
    price: 149.00,
    image: '/servicos/maquiagem.webp',
    category: 'maquiagem',
    available: true,
  },
  {
    id: 'micropig-de-olhos-inferior-definiti',
    name: 'Micropig de Olhos Inferior Definiti',
    description: 'Duração aproximada de 2h.',
    price: 823.00,
    image: '/servicos/maquiagem.webp',
    category: 'maquiagem',
    available: true,
  },
  {
    id: 'micropig-de-olhos-superior-definiti',
    name: 'Micropig de Olhos Superior Definiti',
    description: 'Duração aproximada de 2h.',
    price: 823.00,
    image: '/servicos/maquiagem.webp',
    category: 'maquiagem',
    available: true,
  },
  {
    id: 'micropig-de-sobrancelha',
    name: 'Micropig de Sobrancelha',
    description: 'Duração aproximada de 2h.',
    price: 968.00,
    image: '/servicos/maquiagem.webp',
    category: 'maquiagem',
    available: true,
  },
  {
    id: 'teste-de-maquiagem',
    name: 'Teste de Maquiagem',
    description: 'Duração aproximada de 1h30.',
    price: 76.00,
    image: '/servicos/maquiagem.webp',
    category: 'maquiagem',
    available: true,
  },
  {
    id: 'noiva-hidratacao-capilar',
    name: 'Noiva - Hidratação Capilar',
    description: 'Duração aproximada de 1h.',
    price: 73.00,
    image: '/servicos/noiva.webp',
    category: 'noiva',
    available: true,
  },
  {
    id: 'noiva-maquiagem',
    name: 'Noiva - Maquiagem',
    description: 'Duração aproximada de 1h.',
    price: 293.00,
    image: '/servicos/noiva.webp',
    category: 'noiva',
    available: true,
  },
  {
    id: 'noiva-penteado',
    name: 'Noiva - Penteado',
    description: 'Duração aproximada de 1h.',
    price: 315.00,
    image: '/servicos/noiva.webp',
    category: 'noiva',
    available: true,
  },
  {
    id: 'noiva-preparo',
    name: 'Noiva - Preparo',
    description: 'Duração aproximada de 1h.',
    price: 121.00,
    image: '/servicos/noiva.webp',
    category: 'noiva',
    available: true,
  },
  {
    id: 'noiva-testearranjo',
    name: 'Noiva - Testearranjo',
    description: 'Duração aproximada de 1h.',
    price: 121.00,
    image: '/servicos/noiva.webp',
    category: 'noiva',
    available: true,
  },
  {
    id: 'noiva-testemaquiagem',
    name: 'Noiva - Testemaquiagem',
    description: 'Duração aproximada de 1h.',
    price: 85.00,
    image: '/servicos/noiva.webp',
    category: 'noiva',
    available: true,
  },
];

/* -------------------------------------------------------------------------- */
/* COMBOS — sem checkout não há combo somável.                                 */
/* -------------------------------------------------------------------------- */

export const combos: Combo[] = [];

export function comboAsProduct(combo: Combo): Product {
  const names = combo.productIds
    .map((id) => products.find((p) => p.id === id)?.name)
    .filter(Boolean)
    .join(' + ');

  return {
    id: `combo-${combo.id}`,
    name: combo.name,
    description: names,
    price: combo.comboPrice,
    image: null,
    category: 'combos',
    available: true,
  };
}

export function findSellableById(id: string): Product | undefined {
  const product = products.find((p) => p.id === id);
  if (product) return product;
  const combo = combos.find((c) => `combo-${c.id}` === id);
  return combo ? comboAsProduct(combo) : undefined;
}

/* -------------------------------------------------------------------------- */
/* SOBRE                                                                       */
/* -------------------------------------------------------------------------- */

export const about: AboutSection = {
  title: 'Na Rua Itapeti desde 2021',
  subtitle: 'Salão de beleza no Tatuapé, com equipe nominada e agenda por WhatsApp',
  paragraphs: [
    'O Alooks Hair Studio fica na Rua Itapeti, 518, no Tatuapé. Atende de terça a sábado, das 9h às 20h, com hora marcada.',
    'A equipe tem dez profissionais na escala pública da casa — entre eles Billy, Rita e Mariah, no cabelo, citados nominalmente pelos clientes nas avaliações do Google.',
    'O catálogo vai de corte, coloração e alongamento a depilação, manicure, design de sobrancelhas, maquiagem e serviços para noiva. São 378 serviços com preço publicado pela própria casa.',
  ],
  values: [
    { icon: '', title: '4,9 no Google', description: '102 avaliações da unidade Tatuapé.' },
    { icon: '', title: '378 serviços', description: 'Preço e duração publicados pela casa.' },
    { icon: '', title: 'Hora marcada', description: 'A casa recomenda agendar antes de ir.' },
    { icon: '', title: 'Acessível', description: 'Entrada e banheiro com acessibilidade; Wi-Fi gratuito.' },
  ],
};

/* -------------------------------------------------------------------------- */
/* AVALIAÇÕES                                                                  */
/* -------------------------------------------------------------------------- */
/*
  Avaliações reais do Google (4,9 · 102 avaliações), transcritas literalmente.
  Sem login o Google libera 10 com texto; todas as dez são 5 estrelas.

  A concatenação da RESPOSTA DA LOJA foi procurada explicitamente no DOM
  ('Resposta do proprietário'): ZERO ocorrências. Tudo abaixo é fala de
  cliente. As linhas 'Serviços | ...' que aparecem na ficha são metadado
  estruturado do Google, não texto do avaliador, e ficaram de fora.

  Nome: primeiro nome + inicial. A avaliação é pública; o nome completo não vai.
*/

export const reviews: Review[] = [
  {
    id: 'r-pamella',
    name: 'Pamella V.',
    initials: 'PV',
    rating: 5,
    text: 'Sempre impecável! Mariah deusaaaaaa dos cabelos! Ambiente delicioso, cappuccino e bolo sempre incríveis! Frequento há mais de 10 anos! Amo!',
    date: 'há 2 meses',
  },
  {
    id: 'r-leticia',
    name: 'Letícia H.',
    initials: 'LH',
    rating: 5,
    text: 'Minha mãe e eu somos clientes fiéis há mais de 25 anos. Atendimento de qualidade, profissionais muito competentes e sempre muito atenciosos.',
    date: 'há 2 meses',
  },
  {
    id: 'r-eliza',
    name: 'Eliza Y.',
    initials: 'EY',
    rating: 5,
    text: 'Sempre sou muito bem atendida por todos os profissionais. Conheço o Bily e a Rita de longa data. Sao profissionais exemplares.',
    date: 'há 2 meses',
  },
  {
    id: 'r-maria',
    name: 'Maria M.',
    initials: 'MM',
    rating: 5,
    text: 'Ótimos profissionais, cabeleleiros e manicures excelentes e recepcionistas muito gentis, educadas e atenciosas',
    date: 'há 2 meses',
  },
  {
    id: 'r-liliane',
    name: 'Liliane P.',
    initials: 'LP',
    rating: 5,
    text: 'Atendimento da recepção maravilhoso, e os profissionais mais que qualificados e mais q maravilhosos!! Amoooo todos',
    date: 'há 2 meses',
  },
  {
    id: 'r-bruno',
    name: 'Bruno F.',
    initials: 'BF',
    rating: 5,
    text: 'Lugar incrível, ótimos profissionais. Super bem atendido',
    date: 'há 7 meses',
  },
];

/* -------------------------------------------------------------------------- */
/* FAQ                                                                         */
/* -------------------------------------------------------------------------- */

export const faqs: FAQ[] = [
  {
    question: 'Preciso agendar?',
    answer:
      'A casa recomenda marcar hora. O agendamento é feito pelo WhatsApp — cada serviço desta página abre a conversa já dizendo qual serviço interessa.',
  },
  {
    question: 'Os preços da página são finais?',
    answer:
      'Os valores são os publicados pelo próprio salão, com duração estimada por serviço. Cabelo pode variar com comprimento e volume, então confirme na hora de agendar.',
  },
  {
    question: 'Qual o horário de funcionamento?',
    answer:
      'De terça a sábado, das 9h às 20h. Domingo e segunda a casa não abre.',
  },
  {
    question: 'O espaço é acessível?',
    answer:
      'Sim. A ficha da casa informa entrada e banheiro com acessibilidade para cadeira de rodas, além de Wi-Fi gratuito.',
  },
];
